### PR TITLE
Navigation SDK v0.23.0

### PR DESCRIPTION
**Pull request by 1ec5**
Upgraded to navigation SDK ~~v0.22.0~~ v0.23.0, which changes an initializer signature in a way that only affects the Objective-C setup example.

/cc @JThramer @akitchen @friedbunny

### CODE REVIEW

**Comment by friedbunny** [comment]
@akitchen @JThramer what’s the review status on this?

**Comment by akitchen** [comment]
The change seems simple enough, but the CI task is flaky. what to do?

**Comment by friedbunny** [comment]
@akitchen The flappy tests are in the main maps SDK project and are failing before the navigation target can run, so my suggestion is to rebase this PR onto `master` (now that #237 has landed) and go from there. 🐦 🙇

**Comment by 1ec5** [comment]
Rebased and updated to v0.23.0.

**Pull request merged**
