### PR TITLE
Update for Maps SDK v5.3.0 (queso)

### PR DESCRIPTION
**Pull request by jmkiley**

### CODE REVIEW

**Comment by friedbunny** [comment]
@jmkiley when you bump the pod version, also commit the `Podfile.lock` and project changes (otherwise there’s some inconsistency about which version should be used).

**Comment by jmkiley** [comment]
Ready for review

**Comment by jmkiley** [comment]
Done, @friedbunny

**Comment by friedbunny** [comment]
This was squash merged. 😢

**Pull request merged**
