### PR TITLE
Update for Mapbox iOS SDK v3.7.0

### PR DESCRIPTION
**Pull request by friedbunny**
A branch for working on the future Mapbox iOS SDK v3.7.0 release, for merging upon final release.

/cc @jmkiley @captainbarbosa

### CODE REVIEW

**Comment by friedbunny** [comment]
Rebased this branch to pull in Xcode 9 changes.

**Comment by friedbunny** [comment]
Updated for v3.7.0-beta.2 and rebased on current `master`.

**Comment by jmkiley** [comment]
Added an example for `MGLImageSource`.
simulator screen shot - iphone se - 2017-11-08 at 13 47 50

**Comment by friedbunny** [comment]
Once 3.7.0 is released, we can update the pod and merge this.

**Pull request merged**
